# -*- coding: utf-8 -*-
import unittest

from nose.tools import eq_

from gilded_rose import Item, GildedRose


def assert_item_equals(item, item_name, sell_in, quality):
    eq_(item_name, item.name)
    eq_(sell_in, item.sell_in)
    eq_(quality, item.quality)


def verify_update(updates, name, sell_in, quality, expected_sell_in, expected_quality):
    items = [Item(name, sell_in, quality)]
    gilded_rose = GildedRose(items)
    for _ in range(updates):
        gilded_rose.update_quality()
    assert_item_equals(items[0], name, expected_sell_in, expected_quality)


def test_update_once():
    test_values = [
        ("foo", 0, 0, -1, 0),
        ("foo", 0, 1, -1, 0),
        ("foo", 0, 2, -1, 0),
        ("foo", 0, 3, -1, 1),
        ("foo", 1, 0, 0, 0),
        ("foo", 1, 1, 0, 0),
        ("foo", 1, 2, 0, 1),
        ("foo", 1, 3, 0, 2),
        ("foo", 2, 0, 1, 0),
        ("foo", 2, 1, 1, 0),
        ("foo", 2, 2, 1, 1),
        ("foo", 2, 3, 1, 2),
        ("foo", 3, 0, 2, 0),
        ("foo", 3, 1, 2, 0),
        ("foo", 3, 2, 2, 1),
        ("foo", 3, 3, 2, 2),
        ("Aged Brie", 0, 0, -1, 2),
        ("Aged Brie", 0, 1, -1, 3),
        ("Aged Brie", 0, 2, -1, 4),
        ("Aged Brie", 0, 3, -1, 5),
        ("Aged Brie", 0, 49, -1, 50),
        ("Aged Brie", 0, 50, -1, 50),
        ("Aged Brie", 1, 0, 0, 1),
        ("Aged Brie", 1, 1, 0, 2),
        ("Aged Brie", 1, 2, 0, 3),
        ("Aged Brie", 1, 3, 0, 4),
        ("Aged Brie", 2, 0, 1, 1),
        ("Aged Brie", 2, 1, 1, 2),
        ("Aged Brie", 2, 2, 1, 3),
        ("Aged Brie", 2, 3, 1, 4),
        ("Aged Brie", 3, 0, 2, 1),
        ("Aged Brie", 3, 1, 2, 2),
        ("Aged Brie", 3, 2, 2, 3),
        ("Aged Brie", 3, 3, 2, 4),
        ("Aged Brie", 3, 49, 2, 50),
        ("Aged Brie", 3, 50, 2, 50),
        ("Backstage passes to a TAFKAL80ETC concert", -1, 0, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", -1, 1, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", -1, -1, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", -1, -2, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", -1, -3, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", -1, -4, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 0, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 1, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 2, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 3, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 0, 0, 3),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 1, 0, 4),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 2, 0, 5),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 3, 0, 6),
        ("Backstage passes to a TAFKAL80ETC concert", 5, 0, 4, 3),
        ("Backstage passes to a TAFKAL80ETC concert", 5, 1, 4, 4),
        ("Backstage passes to a TAFKAL80ETC concert", 5, 2, 4, 5),
        ("Backstage passes to a TAFKAL80ETC concert", 5, 3, 4, 6),
        ("Backstage passes to a TAFKAL80ETC concert", 5, 49, 4, 50),
        ("Backstage passes to a TAFKAL80ETC concert", 6, 0, 5, 2),
        ("Backstage passes to a TAFKAL80ETC concert", 6, 1, 5, 3),
        ("Backstage passes to a TAFKAL80ETC concert", 6, 2, 5, 4),
        ("Backstage passes to a TAFKAL80ETC concert", 6, 3, 5, 5),
        ("Backstage passes to a TAFKAL80ETC concert", 10, 0, 9, 2),
        ("Backstage passes to a TAFKAL80ETC concert", 10, 1, 9, 3),
        ("Backstage passes to a TAFKAL80ETC concert", 10, 2, 9, 4),
        ("Backstage passes to a TAFKAL80ETC concert", 10, 3, 9, 5),
        ("Backstage passes to a TAFKAL80ETC concert", 11, 0, 10, 1),
        ("Backstage passes to a TAFKAL80ETC concert", 11, 1, 10, 2),
        ("Backstage passes to a TAFKAL80ETC concert", 11, 2, 10, 3),
        ("Backstage passes to a TAFKAL80ETC concert", 11, 3, 10, 4),
        ("Sulfuras, Hand of Ragnaros", 0, 0, 0, 0),
        ("Sulfuras, Hand of Ragnaros", 0, 1, 0, 1),
        ("Sulfuras, Hand of Ragnaros", 0, 2, 0, 2),
        ("Sulfuras, Hand of Ragnaros", 0, 3, 0, 3),
        ("Sulfuras, Hand of Ragnaros", 1, 0, 1, 0),
        ("Sulfuras, Hand of Ragnaros", 1, 1, 1, 1),
        ("Sulfuras, Hand of Ragnaros", 1, 2, 1, 2),
        ("Sulfuras, Hand of Ragnaros", 1, 3, 1, 3),
        ("Sulfuras, Hand of Ragnaros", 2, 0, 2, 0),
        ("Sulfuras, Hand of Ragnaros", 2, 1, 2, 1),
        ("Sulfuras, Hand of Ragnaros", 2, 2, 2, 2),
        ("Sulfuras, Hand of Ragnaros", 2, 3, 2, 3),
        ("Sulfuras, Hand of Ragnaros", 3, 0, 3, 0),
        ("Sulfuras, Hand of Ragnaros", 3, 1, 3, 1),
        ("Sulfuras, Hand of Ragnaros", 3, 2, 3, 2),
        ("Sulfuras, Hand of Ragnaros", 3, 3, 3, 3),
    ]
    for test_value in test_values:
        yield verify_update, 1, test_value[0], test_value[1], test_value[2], test_value[3], test_value[4]


def test_update_twice():
    test_values = [
        ("foo", 0, 0, -2, 0),
        ("foo", 0, 1, -2, 0),
        ("foo", 0, 2, -2, 0),
        ("foo", 0, 3, -2, 0),
        ("foo", 1, 0, -1, 0),
        ("foo", 1, 1, -1, 0),
        ("foo", 1, 2, -1, 0),
        ("foo", 1, 3, -1, 0),
        ("foo", 2, 0, 0, 0),
        ("foo", 2, 1, 0, 0),
        ("foo", 2, 2, 0, 0),
        ("foo", 2, 3, 0, 1),
        ("foo", 3, 0, 1, 0),
        ("foo", 3, 1, 1, 0),
        ("foo", 3, 2, 1, 0),
        ("foo", 3, 3, 1, 1),
        ("Aged Brie", 0, 0, -2, 4),
        ("Aged Brie", 0, 1, -2, 5),
        ("Aged Brie", 0, 2, -2, 6),
        ("Aged Brie", 0, 3, -2, 7),
        ("Aged Brie", 1, 0, -1, 3),
        ("Aged Brie", 1, 1, -1, 4),
        ("Aged Brie", 1, 2, -1, 5),
        ("Aged Brie", 1, 3, -1, 6),
        ("Aged Brie", 2, 0, 0, 2),
        ("Aged Brie", 2, 1, 0, 3),
        ("Aged Brie", 2, 2, 0, 4),
        ("Aged Brie", 2, 3, 0, 5),
        ("Aged Brie", 3, 0, 1, 2),
        ("Aged Brie", 3, 1, 1, 3),
        ("Aged Brie", 3, 2, 1, 4),
        ("Aged Brie", 3, 3, 1, 5),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 0, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 1, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 2, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 3, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 0, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 1, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 2, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 3, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 2, 0, 0, 6),
        ("Backstage passes to a TAFKAL80ETC concert", 2, 1, 0, 7),
        ("Backstage passes to a TAFKAL80ETC concert", 2, 2, 0, 8),
        ("Backstage passes to a TAFKAL80ETC concert", 2, 3, 0, 9),
        ("Backstage passes to a TAFKAL80ETC concert", 3, 0, 1, 6),
        ("Backstage passes to a TAFKAL80ETC concert", 3, 1, 1, 7),
        ("Backstage passes to a TAFKAL80ETC concert", 3, 2, 1, 8),
        ("Backstage passes to a TAFKAL80ETC concert", 3, 3, 1, 9),
        ("Sulfuras, Hand of Ragnaros", 0, 0, 0, 0),
        ("Sulfuras, Hand of Ragnaros", 0, 1, 0, 1),
        ("Sulfuras, Hand of Ragnaros", 0, 2, 0, 2),
        ("Sulfuras, Hand of Ragnaros", 0, 3, 0, 3),
        ("Sulfuras, Hand of Ragnaros", 1, 0, 1, 0),
        ("Sulfuras, Hand of Ragnaros", 1, 1, 1, 1),
        ("Sulfuras, Hand of Ragnaros", 1, 2, 1, 2),
        ("Sulfuras, Hand of Ragnaros", 1, 3, 1, 3),
        ("Sulfuras, Hand of Ragnaros", 2, 0, 2, 0),
        ("Sulfuras, Hand of Ragnaros", 2, 1, 2, 1),
        ("Sulfuras, Hand of Ragnaros", 2, 2, 2, 2),
        ("Sulfuras, Hand of Ragnaros", 2, 3, 2, 3),
        ("Sulfuras, Hand of Ragnaros", 3, 0, 3, 0),
        ("Sulfuras, Hand of Ragnaros", 3, 1, 3, 1),
        ("Sulfuras, Hand of Ragnaros", 3, 2, 3, 2),
        ("Sulfuras, Hand of Ragnaros", 3, 3, 3, 3),
    ]
    for test_value in test_values:
        yield verify_update, 2, test_value[0], test_value[1], test_value[2], test_value[3], test_value[4]


def test_update_trice():
    test_values = [
        ("foo", 0, 0, -3, 0),
        ("foo", 0, 1, -3, 0),
        ("foo", 0, 2, -3, 0),
        ("foo", 0, 3, -3, 0),
        ("foo", 1, 0, -2, 0),
        ("foo", 1, 1, -2, 0),
        ("foo", 1, 2, -2, 0),
        ("foo", 1, 3, -2, 0),
        ("foo", 2, 0, -1, 0),
        ("foo", 2, 1, -1, 0),
        ("foo", 2, 2, -1, 0),
        ("foo", 2, 3, -1, 0),
        ("foo", 3, 0, 0, 0),
        ("foo", 3, 1, 0, 0),
        ("foo", 3, 2, 0, 0),
        ("foo", 3, 3, 0, 0),
        ("foo", 4, 0, 1, 0),
        ("foo", 4, 1, 1, 0),
        ("foo", 4, 2, 1, 0),
        ("foo", 4, 3, 1, 0),
        ("foo", 4, 4, 1, 1),
        ("Aged Brie", 0, 0, -3, 6),
        ("Aged Brie", 0, 1, -3, 7),
        ("Aged Brie", 0, 2, -3, 8),
        ("Aged Brie", 0, 3, -3, 9),
        ("Aged Brie", 1, 0, -2, 5),
        ("Aged Brie", 1, 1, -2, 6),
        ("Aged Brie", 1, 2, -2, 7),
        ("Aged Brie", 1, 3, -2, 8),
        ("Aged Brie", 2, 0, -1, 4),
        ("Aged Brie", 2, 1, -1, 5),
        ("Aged Brie", 2, 2, -1, 6),
        ("Aged Brie", 2, 3, -1, 7),
        ("Aged Brie", 3, 0, 0, 3),
        ("Aged Brie", 3, 1, 0, 4),
        ("Aged Brie", 3, 2, 0, 5),
        ("Aged Brie", 3, 3, 0, 6),
        ("Aged Brie", 4, 0, 1, 3),
        ("Aged Brie", 4, 1, 1, 4),
        ("Aged Brie", 4, 2, 1, 5),
        ("Aged Brie", 4, 3, 1, 6),
        ("Aged Brie", 4, 4, 1, 7),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 0, -3, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 1, -3, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 2, -3, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 0, 3, -3, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 0, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 1, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 2, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 1, 3, -2, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 2, 0, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 2, 1, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 2, 2, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 2, 3, -1, 0),
        ("Backstage passes to a TAFKAL80ETC concert", 3, 0, 0, 9),
        ("Backstage passes to a TAFKAL80ETC concert", 3, 1, 0, 10),
        ("Backstage passes to a TAFKAL80ETC concert", 3, 2, 0, 11),
        ("Backstage passes to a TAFKAL80ETC concert", 3, 3, 0, 12),
        ("Backstage passes to a TAFKAL80ETC concert", 4, 0, 1, 9),
        ("Backstage passes to a TAFKAL80ETC concert", 4, 1, 1, 10),
        ("Backstage passes to a TAFKAL80ETC concert", 4, 2, 1, 11),
        ("Backstage passes to a TAFKAL80ETC concert", 4, 3, 1, 12),
        ("Backstage passes to a TAFKAL80ETC concert", 4, 4, 1, 13),
        ("Sulfuras, Hand of Ragnaros", 0, 0, 0, 0),
        ("Sulfuras, Hand of Ragnaros", 0, 1, 0, 1),
        ("Sulfuras, Hand of Ragnaros", 0, 2, 0, 2),
        ("Sulfuras, Hand of Ragnaros", 0, 3, 0, 3),
        ("Sulfuras, Hand of Ragnaros", 1, 0, 1, 0),
        ("Sulfuras, Hand of Ragnaros", 1, 1, 1, 1),
        ("Sulfuras, Hand of Ragnaros", 1, 2, 1, 2),
        ("Sulfuras, Hand of Ragnaros", 1, 3, 1, 3),
        ("Sulfuras, Hand of Ragnaros", 2, 0, 2, 0),
        ("Sulfuras, Hand of Ragnaros", 2, 1, 2, 1),
        ("Sulfuras, Hand of Ragnaros", 2, 2, 2, 2),
        ("Sulfuras, Hand of Ragnaros", 2, 3, 2, 3),
        ("Sulfuras, Hand of Ragnaros", 3, 0, 3, 0),
        ("Sulfuras, Hand of Ragnaros", 3, 1, 3, 1),
        ("Sulfuras, Hand of Ragnaros", 3, 2, 3, 2),
        ("Sulfuras, Hand of Ragnaros", 3, 3, 3, 3),
        ("Sulfuras, Hand of Ragnaros", 4, 0, 4, 0),
        ("Sulfuras, Hand of Ragnaros", 4, 1, 4, 1),
        ("Sulfuras, Hand of Ragnaros", 4, 2, 4, 2),
        ("Sulfuras, Hand of Ragnaros", 4, 3, 4, 3),
        ("Sulfuras, Hand of Ragnaros", 4, 4, 4, 4),
    ]
    for test_value in test_values:
        yield verify_update, 3, test_value[0], test_value[1], test_value[2], test_value[3], test_value[4]

if __name__ == '__main__':
    unittest.main()
